version: "3"

services:
  wiremock:
    container_name: my_wiremock
    image: "wiremock/wiremock:latest"
    ports:
      - 8080:8080
    volumes:
      - ./wiremock/extensions:/home/wiremock/extensions
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    
  db:
    container_name: my_postgres
    image: "postgres:16"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
      TZ: Asia/Tokyo

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres/data
      o: bind
